services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./web/images:/usr/share/nginx/html/images:ro
      - ./web/conf.d:/etc/nginx/conf.d:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    networks:
      - network1

  web-proxy:
    build:
      context: ./web-proxy
    container_name: web-proxy
    volumes:
      - ./web-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./web-proxy/conf.d:/etc/nginx/conf.d:ro
    ports:
      - "80:80"
    networks:
      - network1
    depends_on:
      - web

  test:
    build: 
      context: ./tests
    volumes:
      - ./tests/scripts:/scripts
    networks:
      - network1

networks:
  network1:
