name: prctr-hsa-hw16

services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./web/published_content:/usr/share/nginx/html:ro
      - ./web/conf.d:/etc/nginx/conf.d:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "5080:80"
    networks:
      - network1
    deploy:
      resources:
        limits:
          cpus: '0.1'
    expose:
      - "0-65535/udp"

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    ports:
      - "80:80"
    volumes:
      - ./kali:/kali:rw
    networks:
      - network1
    command: tail -f /dev/null

networks:
  network1:
