name: prctr-hsa-hw16

services:
  web:
    image: nginx:alpine
    container_name: web
    volumes:
      - ./web/published_content:/usr/share/nginx/html:ro
      - ./web/conf.d:/etc/nginx/conf.d:ro
      - ./web/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    networks:
      - network1

  kali:
    image: kalilinux/kali-rolling
    container_name: kali
    ports:
      - "80:80"
    volumes:
      - ./kali:/kali:rw
    networks:
      - network1

networks:
  network1:
