FROM kalilinux/kali-rolling
# RUN apt update && apt install -y kali-linux-large
# apt update && apt -y install kali-linux-headless
RUN apt-get update && apt-get install -y hping3 iputils-ping apache2-utils slowloris nmap
#RUN apt update && apt install -y kali-linux-large
